Fix polars dependency (#30)
The error was:
```
The conflict is caused by:
ERROR: ResolutionImpossible: for help visit
https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
    paradigm-flood 0.3.0a0 depends on polars<0.19 and >=0.18.7
    checkthechain 0.3.9 depends on polars<0.18 and >=0.17.3
```
Refs:
https://github.com/paradigmxyz/flood/actions/runs/5571608157/jobs/10176802894